# Generated by Django 3.0.5 on 2021-02-20 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Food', 'Food'), ('Fitness', 'Fitness')], default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='', max_length=3000)),
                ('cover_image', models.ImageField(upload_to='media/cover_images')),
                ('author', models.CharField(default='Nishant Gada', max_length=300)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_form_enquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=500)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
