# Generated by Django 3.0.5 on 2021-02-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form_enquire',
            new_name='Contact_form_enquirie',
        ),
    ]
