# Generated by Django 3.0.5 on 2021-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210220_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
