# Generated by Django 3.0.5 on 2021-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210222_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
