# Generated by Django 3.0.5 on 2021-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210222_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='category',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.ManyToManyField(to='App.Categorie'),
        ),
    ]
