# Generated by Django 3.0.5 on 2021-03-10 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210225_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
